"""etapa 3: marcas de validacion

Revision ID: 77487edc8e78
Revises: e9867cccff50
Create Date: 2026-09-23 00:37:20.161785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77487edc8e78'
down_revision: Union[str, Sequence[str], None] = 'e9867cccff50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mark_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mark_id'], ['validation_marks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mark_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('mark_id', sa.Integer(), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('x0', sa.Integer(), nullable=False),
    sa.Column('y0', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=False),
    sa.Column('y1', sa.Integer(), nullable=False),
    sa.Column('crop_path', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('verifier', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['mark_id'], ['validation_marks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('submissions', sa.Column('mark_status', sa.String(length=20), nullable=True))
    op.add_column('submissions', sa.Column('mark_detail', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('mark_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'mark_confirmed')
    op.drop_column('submissions', 'mark_detail')
    op.drop_column('submissions', 'mark_status')
    op.drop_table('mark_detections')
    op.drop_table('mark_references')
    op.drop_table('validation_marks')
    # ### end Alembic commands ###
