"""modo solo firma

Revision ID: a2664da6a3bb
Revises: a32b2d104858
Create Date: 2026-10-01 15:55:32.761574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2664da6a3bb'
down_revision: Union[str, Sequence[str], None] = 'a32b2d104858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('grading_mode', sa.String(length=20), server_default='ejercicios', nullable=False))
    op.add_column('assignments', sa.Column('unsigned_score', sa.Float(), server_default='90', nullable=False))
    op.add_column('assignments', sa.Column('unsigned_comment', sa.Text(), server_default='La actividad tiene que estar firmada', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'unsigned_comment')
    op.drop_column('assignments', 'unsigned_score')
    op.drop_column('assignments', 'grading_mode')
    # ### end Alembic commands ###
