"""etapa 5: panel de revision

Revision ID: a32b2d104858
Revises: 995dc325b8d0
Create Date: 2026-09-29 18:59:14.404830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32b2d104858'
down_revision: Union[str, Sequence[str], None] = '995dc325b8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('score_override', sa.Float(), nullable=True))
    op.add_column('submissions', sa.Column('comment_override', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('captured', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'captured')
    op.drop_column('submissions', 'comment_override')
    op.drop_column('submissions', 'score_override')
    # ### end Alembic commands ###
