"""etapa 2: tareas, entregas y paginas

Revision ID: e9867cccff50
Revises: 86579ac477bc
Create Date: 2026-09-23 00:19:40.019420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9867cccff50'
down_revision: Union[str, Sequence[str], None] = '86579ac477bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('coursework_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('mark_module_enabled', sa.Boolean(), nullable=False),
    sa.Column('minor_error_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'coursework_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('classroom_submission_id', sa.String(length=64), nullable=False),
    sa.Column('student_user_id', sa.String(length=64), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('alternate_link', sa.String(length=500), nullable=False),
    sa.Column('classroom_state', sa.String(length=32), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.Column('attachment_ids', sa.Text(), nullable=False),
    sa.Column('download_status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'classroom_submission_id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    op.drop_table('submissions')
    op.drop_table('assignments')
    # ### end Alembic commands ###
